# -*- coding: utf-8 -*-
"""hackathon 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iT8AwRZMyQZTkVNjv_X3iHfJaGXvhcU4
"""

city_data = [
["A1", 1540, 120],
["B2", 980, 95],
["C3", 2300, 170],
["A1", 1400, 115],
["C3", 2500, 180],
["B2", 1020, 100],
["D4", 800, 85],
["E5", 2600, 190],
["A1", 1600, 130],
["C3", 2100, 160]
]

count=0
for i in city_data:
  count+=1
print("Total Records:",count)

unique=set()
for i in city_data:
 unique.add(i[0])
print(unique)


print("====Junction-wise Average Data:==== ")

a_total=0
a_count=0
a_aqi=0
b_total=0
b_count=0
b_aqi=0
c_total=0
c_count=0
c_aqi=0
d_total=0
d_count=0
d_aqi=0
e_total = 0
e_aqi = 0
e_count = 0


for i in city_data:
  if i[0]=="A1":
   a_total=a_total+i[1]
   a_aqi=a_aqi+i[2]
   a_count=a_count+1
   avg_aqi=a_aqi/a_count
if avg_aqi <= 100:
    level = "Good"
elif avg_aqi <= 150:
    level = "Moderate"
else:
    level = "Unhealthy"
print(f"A1 -> Avg Vehicles: {a_total/a_count:.10f} | Avg AQI: {a_aqi/a_count:.1f} | {level}")

for i in city_data:
  if i[0]=="B2":
    b_total=b_total+i[1]
    b_aqi=b_aqi+i[2]
    b_count+=1
    avg_aqi=b_aqi/b_count
if avg_aqi <= 100:
    level = "Good"
elif avg_aqi <= 150:
    level = "Moderate"
else:
    level = "Unhealthy"
print(f"B2 -> Avg Vehicles: {b_total/b_count:.1f} | Avg AQI: {b_aqi/b_count:.1f}  | {level}")

for i in city_data:
  if i[0]=="C3":
    c_total=c_total+i[1]
    c_aqi=c_aqi+i[2]
    c_count+=1
    avg_aqi=c_aqi/c_count
if avg_aqi <= 100:
    level = "Good"
elif avg_aqi <= 150:
    level = "Moderate"
else:
    level = "Unhealthy"
print(f"C3 -> Avg Vehicles: {c_total/c_count:.1f} | Avg AQI: {c_aqi/c_count:.1f} | {level}")

for i in city_data:
  if i[0]=="D4":
    d_total=d_total+i[1]
    d_aqi=d_aqi+i[2]
    d_count+=1
    avg_aqi=d_aqi/d_count
if avg_aqi <= 100:
    level = "Good"
elif avg_aqi <= 150:
    level = "Moderate"
else:
    level = "Unhealthy"
print(f"D4 -> Avg Vehicles: {d_total/d_count:.1f}  | Avg AQI: {d_aqi/d_count:.1f}  | {level}")

for i in city_data:
  if i[0]=="E5":
    e_total=e_total+i[1]
    e_aqi=e_aqi+i[2]
    e_count+=1
    avg_aqi= e_aqi/e_count
if avg_aqi <= 100:
    level = "Good"
elif avg_aqi <= 150:
    level = "Moderate"
else:
    level = "Unhealthy"
print(f"E5 -> Avg Vehicles: {e_total/e_count:.1f} | Avg AQI: {e_aqi/e_count:.1f} | {level}")

max=-999
city=""
for i in city_data:
  if i[2]>max:
    max=i[2]
    city=i[0]
print("most polluted junction",city)

city_name=""
max_vehicles=0
for i in city_data:
  if i[1]>max_vehicles:
    max_vehicles=i[1]
    city_name=i[0]
print("highest average vehicle count junction",city_name)


print("=====THANKYOU=====")

